# Generated by Django 5.2.7 on 2025-12-01 14:50

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('ci', models.CharField(max_length=20, unique=True, verbose_name='Cédula de Identidad')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('100.00'))], verbose_name='Monto del Préstamo')),
                ('tasa_interes_anual', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Tasa de Interés Anual (%)')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('plazo', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(360)], verbose_name='Plazo en Meses')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Amortizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveIntegerField(verbose_name='N° Cuota')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('cuota', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cuota')),
                ('capital', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Capital (Amortización)')),
                ('interes', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Interés')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Saldo Restante')),
                ('pagado', models.BooleanField(default=False, verbose_name='¿Pagado?')),
                ('fecha_pago_real', models.DateField(blank=True, null=True, verbose_name='Fecha de Pago Real')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amortizaciones', to='creditos.prestamo', verbose_name='Préstamo')),
            ],
            options={
                'verbose_name': 'Cuota de Amortización',
                'verbose_name_plural': 'Cuotas de Amortización',
                'ordering': ['prestamo', 'numero_cuota'],
                'unique_together': {('prestamo', 'numero_cuota')},
            },
        ),
    ]
